# Use cargo to test the project
variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo

test:nightly:
  image: rustlang/rust:nightly
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo +nightly test --all --verbose --features std # Test with `std` enabled
  cache:
    paths:
      - cargo/
      - target/

test:no_std:
  image: rustlang/rust:nightly
  script:
  - rustc --version && cargo --version
  - cargo +nightly test --all --verbose --no-default-features
  cache:
    paths:
      - cargo/
      - target/

test:stable:
  image: "rust:latest"
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose --features std # Test with `std` enabled
  cache:
    paths:
      - cargo/
      - target/

