# Use cargo to test the project
image: "rust:latest"

test:std:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo +stable test --all --verbose --features std # Test with `std` enabled

test:nightly:
  script:
  - rustup toolchain add nightly
  - rustup default nightly
  - rustc --version && cargo --version
  - cargo +nightly test --all --verbose --no-default-features