# Use cargo to test the project
image: "rust:nightly"

test:std:
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose --features std # Test with `std` enabled

test:no_std:
  script:
  - rustc --version && cargo --version
  - cargo +nightly test --all --verbose --no-default-features