[package]
name = "small"
version = "0.1.0"
authors = ["Tom Almeida <tommoa256@gmail.com>"]

[features]
default = ["std", "serde"]
std = []

[dependencies]
serde = {version = "1.0.70", optional = true}

[dev-dependencies]
serde_json = "1.0.24"
